apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-replicas
  labels:
    app: myapp
    tyoe: front-end
spec:
  template:
    metadata: #can only have name and value
      name: myapp-pod #string value
      labels: # can have any key and value under here (this is is a dictionary)
        app: myapp
        type: myapp-frontend
    spec:
      containers: #property is a list/array
        - name: nginx-container #dash symbolizes the first item in the list.
          image: nginx
    replicas: 3