apiVersion: apps/v1 
kind: Deployment
metadata:
  name: zufarexplainedit-hello-app
  labels: 
     app: hello-app

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: hello-app

  template:
    metadata:
      labels:
        app: hello-app
    spec:
      containers:
      - name: hello-app
        image: zufarexplainedit/hello
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1