apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgress
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-persistenct-volume-claim
      containers:
        - name: postgres
          image: fhinschy/notes-postgress
          ports:
            - containerPort: 5342

            # Volume mounting configurations for the data
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: 483yr40ryy038
            - name: POSTGRES_DB
              value: notesdb